# おまじない
version: "3"
# コンテナの一覧を書く合図
services:
  # コンテナの名前
  python-test:
    # このフォルダにあるDokerfileを使う
    build: .
    # ホストの"."とコンテナ内の"app"を同期（これがないとコンテナを消したらファイルが消える）
    volumes:
      - .:/app
    # ターミナルを使えるようにする設定
    tty: true